* Emacs使用
** 常用命令
   #+begin_example
   M-x package-list-packages  查看包
   #+end_example
** emacs配置国内源
   http://elpa.emacs-china.org
   #+begin_src lisp
   (setq package-archives '(("gnu"   . "http://elpa.emacs-china.org/gnu/")
                         ("melpa" . "http://elpa.emacs-china.org/melpa/")))
   #+end_src
** 主题配置
https://emacsthemes.com/
** 使用Ivy增强emacs的功能
https://github.com/abo-abo/swiper
Emacs中许多默认功能使用起来都不是很方便，比如M-x不能自动补全，使用Ivy来增强emacs的功能。
Ivy包含3个插件：Ivy、Counsel、Swiper
*** 安装Ivy
** use-package
https://github.com/jwiegley/use-package

** magit
https://github.com/magit/magit

** 重新加载配置文件
每次编辑完~/.emacs.d/init.el配置文件，是不会自动生效的，需要重新启动emacs。
但是每次重新启动emacs确实挺麻烦的，可以通过下面两个方法是配置文件生效
1. 使用`M-x load-file` 来重新加载配置
2. 使用`C-x C-e` 执行配置文件中lisp代码 

** 使用中遇到的问题
*** org-model <s + tab 不起作用了
https://orgmode.org/Changes_old.html
Change in the structure template expansion
Org 9.2 comes with a new template expansion mechanism, combining org-insert-structure-template bound to C-c C-,.
If you customized the org-structure-template-alist option manually, you probably need to udpate it, see the docstring for accepted values.
If you prefer using previous patterns, e.g. <s, you can activate them again by requiring Org Tempo library:
(require 'org-tempo)
or add it to org-modules.
If you need complex templates, look at the tempo-define-template function or at solutions like Yasnippet.
